// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arrxccemekakpaoqhuca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFycnhjY2VtZWtha3Bhb3FodWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDk3NzksImV4cCI6MjA2OTMyNTc3OX0.I-Pmjidtj_KEhxhUv8Vv9xUeuxH4osZ8t_Nf43PTBCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});